### PR TITLE
fix keyboard making the game shut down on receiving tables

### PR DESCRIPTION
**Pull request by DS-Minetest**
The title should say enough.
I also made the spaces to tabs.
The only real change is in line 33. (Or look into first commit only, there it's readable.)

### CODE REVIEW

**Comment by DS-Minetest** [comment]
@numberZero This PR is important, server owners won't like or use the mod if it always shuts down the server. Let's make digiline-stuff ~~great again~~ usable for servers and not only for singleplayer!

**Comment by numberZero** [comment]
@DS-Minetest Merged as is. But note that I don’t plan to resurrect this mod anymore. Newer mods should supersede this IMO.

**Comment by numberZero** [comment]
E.g. https://github.com/numberZero/minetest-digiline_memory
Note that it is **not** based on the original digiline-stuff anymore (but similar code is present here as I have committed it to this repository earlier)

**Comment by DS-Minetest** [comment]
Yes, it's also nice, that you took a different name (without `s`), so, that both can be used at once.

> But note that I don’t plan to resurrect this mod anymore. Newer mods should supersede this IMO.

(Then the branch name "nextgen" is a bit confusing.) This mod is still one of the most important digiline additions and it doesn't look like anyone would make new mods to supersede this modpack.
Perhaps I will resurrect and maintain this in a fork.

It's sad, that digilines isn't used that much, it can be much fun and useful in game.

**Comment by numberZero** [comment]
> Then the branch name "nextgen" is a bit confusing.

I said “anymore.” I wanted to make this mod work, but found it easier to write everything from scratch.

**Pull request merged**
